# -*- coding: utf-8 -*-
{
    'name': 'roc_custom',
    'version': '1.0',
    'category': 'Custom',
    'sequence': 15,
    'summary': 'Odoo v15 module with custom features for roc project',
    'description': "",
    'website': '',
    'depends': [
        'crm',
        'roc_crm',
        'roc_sales',
        'roc_quotation',
        'account',
        'sale',
        'fleet',
        'stock',
        'sale_stock',
        'purchase_stock',
        'web_widget_open_tab',
        'web_m2x_options',
        'web_domain_field',
    ],
    'data': [
        'security/groups.xml',
        'wizards/change_date_due_wiz.xml',
        'wizards/lost_reason.xml',
        'wizards/crm_convert_opp_wizard.xml',
        'wizards/sale_purchase_order_wizard_view.xml',
        'wizards/generate_sale_quotation_wizard.xml',
        'wizards/supplierinfo_import_view.xml',
        'views/purchase_order_report.xml',
        'views/sales_complementary_models.xml',
        'views/stock_picking.xml',
        'views/account_journal_view.xml',
        'views/account_move.xml',
        'views/invoice_report.xml',
        'views/mail_template_view.xml',
        'views/crm_lead.xml',
        'views/purchase_order.xml',
        'views/sale_order.xml',
        'views/res_partner.xml',
        'views/mrp_production.xml',
        'views/crm_complementary_models_views.xml',
        'data/intrest_tag.xml',
        'security/ir.model.access.csv',
    ],
    "assets": {
        "web.assets_backend": ["roc_custom/static/src/js/purchase_stock_widget.js","roc_custom/static/src/js/widget.js","roc_custom/static/src/css/custom_css.css"],
        "web.assets_qweb": ["roc_custom/static/src/xml/template.xml","roc_custom/static/src/xml/template_stock_wid.xml","roc_custom/static/src/xml/purchase_stock.xml"],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
