from . import crm_convert_opp_wizard
from . import generate_sale_quotation
from . import supplierinfo_import
from . import change_date_due_wiz
from . import sale_purchase_order_wizard
from . import sale_make_invoice_advance
from . import account_payment_register
from . import modify_tags_masive_wizard
from . import payroll_account_import
from . import mail_compose_message
from . import change_aml_tax_wiz
from . import mrp_alternative_product_assistant
from . import po_alternative_additional_product_assistant
from . import technical_job_assistant_quick_create
from . import massive_pos_billing
