from . import crm_lead
from . import res_partner
from . import crm_complementary_models
from . import purchase_order_line
from . import purchase_order
from . import stock_picking
from . import sale_order
#from . import sale_order_line
from . import mrp_production
from . import mail_template
from . import account_move
from . import crm_lead_visit