from . import crm_lead
from . import res_partner
from . import crm_complementary_models
from . import purchase_order_line
from . import purchase_order
from . import stock_picking
from . import sale_order
#from . import sale_order_line
from . import mrp_production
from . import mail_template
from . import account_move
from . import technical_job
from . import hr_employee
from . import ir_sequence
from . import technical_job_assistant
from . import product_template
from . import product_product
from . import stock_quant
from . import report_stock_forecasted
from . import pos_order
from . import product_template_attribute_value
from . import sale_order_template
from . import res_company
from . import technical_job_time_register
from . import technical_job_note_assistant
from . import technical_job_complementary_models
from . import technical_job_mixing
from . import technical_job_schedule
from . import technical_job_checklist